### ISSUE TITLE
Durable nonces for reliable transactions

### ISSUE THREAD

**Issue by mocolicious** [kinnytips/kinetic#22]

**Comment by mocolicious** [comment]
## Phase 1 - Reliable transactions using nonces
- [ ] implement e2e tests
- [ ] implement ability to use durable nonces for transactions
   - [ ] optional nonce accounts
   - [ ] Nonce authority to fee payer wallet
   - [ ] Advancing of nonce account by Kinetic at regular intervals
- [ ] update documentation

## Phase 2 - Offline sending
- [ ] Offline sending 
   - [ ] Reliable sending P2P offline
   - [ ]  safeguards for reliable failure
- [ ] implement e2e tests
- [ ] test failure scenarios
- [ ] update documentation
