### ISSUE TITLE
from Kin-labs: Checklist for Kinetic Beta

### ISSUE THREAD

**Issue by mocolicious** [kinnytips/kinetic#4]
## Priority 1 (Beta)
- [x] implement e2e tests https://github.com/kin-labs/kinetic/issues/35
- [x] implement health endpoint https://github.com/kin-labs/kinetic/issues/34
- [x]  https://github.com/kin-labs/kinetic/issues/120
- [x] https://github.com/kin-labs/kinetic/issues/110
- [x] https://github.com/kin-labs/kinetic/issues/78
- [x] Admin API https://github.com/kin-labs/kinetic/issues/71
   - [x] implement Authenticated endpoints https://github.com/kin-labs/kinetic/pull/81
   - [x] Management of Apps https://github.com/kin-labs/kinetic/pull/85
   - [x]  Management of Users https://github.com/kin-labs/kinetic/pull/86
   - [x] Management of App User https://github.com/kin-labs/kinetic/pull/88
   - [x] Management of App Wallets https://github.com/kin-labs/kinetic/pull/90
   - [x]  Implement Admin UI to manage the above
- [x] https://github.com/kin-labs/kinetic/issues/104
- [x] https://github.com/kin-labs/kinetic/issues/138
- [x] https://github.com/kin-labs/kinetic/issues/106
- [x] https://github.com/kin-labs/kinetic/issues/109
- [x] https://github.com/kin-labs/kinetic/issues/107
- [x] https://github.com/kin-labs/kinetic/issues/105
- [ ] https://github.com/kin-labs/kinetic/issues/108 TODO: Recreate issue
- [x] https://github.com/kin-labs/kinetic/issues/139
- [ ] https://github.com/kin-labs/kinetic/issues/125 TODO: Recreate issue

## Priority 2 (Pre-release)
- [x] https://github.com/kin-labs/kinetic/issues/114
- [x] https://github.com/kin-labs/kinetic/issues/168
- [x] https://github.com/kin-labs/kinetic/issues/173
- [x] https://github.com/kin-labs/kinetic/issues/166
- [x] https://github.com/kin-labs/kinetic/issues/181
- [x] https://github.com/kin-labs/kinetic/issues/121
- [x] https://github.com/kin-labs/kinetic/issues/217
- [ ] https://github.com/kin-labs/kinetic/issues/218
- [ ] Add Rate limiting to the API
- [ ] Logging https://github.com/kin-labs/kinetic/pull/405
- [ ] Add 'sender create' functionality https://github.com/kin-labs/kinetic/pull/316
- [ ] Make SDKs send their user agent https://github.com/kin-labs/kinetic/issues/377
- [x] https://github.com/kin-labs/kinetic/issues/356
- [x] https://github.com/kin-labs/kinetic/issues/357

## Priority 3 (Release) 
TODO
